version: "3.9"
services:
  db:
    image: postgis/postgis:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - ${DB_HOST}
    # networks:
    #   - default
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./.env
  backend:
    build: ./backend
    command: uvicorn main:app  --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/backend_app
    ports:
      - 8001:8000
    # networks:
    #   - default
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_HOST}/${DB_DATABASE}
    env_file:
      - ./.env
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - 8051:8051
    # networks:
    #   - default
    # network_mode: host
    env_file:
      - ./.env
    depends_on:
      - backend

volumes:
  postgres_data:
networks:
  default:
  # outside:
  #   external: true
